name: Build and Deploy to Azure ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Incremental Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: myprofileacr2026.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            myprofileacr2026.azurecr.io/profile-app:latest
            myprofileacr2026.azurecr.io/profile-app:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Remove Existing Azure Container Instance
        run: |
          az container delete \
            --resource-group profile-app-rg \
            --name my-java-profile-instance \
            --yes \
            || true

      - name: Deploy Commit Version to Azure Container Instance
        run: |
          az container create \
            --resource-group profile-app-rg \
            --name my-java-profile-instance \
            --image myprofileacr2026.azurecr.io/profile-app:${{ github.sha }} \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --registry-login-server myprofileacr2026.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label my-java-profile-sati \
            --ports 80 \
            --environment-variables SERVER_PORT=80 \
            --ip-address Public
